title:            James Pustejovsky
description:      James Pustejovsky's Website

# put your disqus here
disqus_shortname:
reading_time:     false # if true, shows the estimated reading time for a post
words_per_minute: 200
logo:             images/logo.png # logo visible in the topbar
excerpt_separator: <!--more-->
# Your site's domain goes here (eg: //mmistakes.github.io, http://mademistakes.com, etc)
# When testing locally leave blank or use http://localhost:4000

url: http://aronbordin.com/neo-hpstr-jekyll-theme

# draw your top menu here
# each item must have a title and a url.
#   To list post categories. use type: 'categories'
#   To create sub categories. add a submenu item
# See the example
menu:
#  - title: 'Home'
#    url: '/'
  - title: 'NEWS & UPDATES'
    url: '/updates'
  - title: 'PUBLICATIONS'
    submenu:
      - title: 'Books'
        url: '/books'
      - title: 'Journal Articles'
        url: '/articles'
      - title: 'Book Chapters'
        url: '/chapters'
      - title: 'Encyclopedia Entries'
        url: '/encyclopedia'
      - title: 'Conference Proceedings'
        url: '/conferences'
  - title: 'COURSES'
    url: '/courses'
  - title: 'RESEARCH'
    url: '/research'
  - title: 'LINKS'
    submenu:
      - title: 'TimeML'
        url: 'http://www.timeml.org/'
      - title: 'MA Programs in CL'
        url: 'http://www.brandeis.edu/programs/comp-linguistics/'
      - title: 'ISO-Space'
        url: 'https://sites.google.com/site/wikiisospace/'
      - title: 'CS at Brandeis'
        url: 'http://www.cs.brandeis.edu/'
  - title: 'SPECIAL COURSES'
    submenu:
      - title: 'EACL 2017'
        url: 'http://www.voxicon.net/eacl-2017/eacl-2017-tutorial-materials/'

# Owner/author information
owner:
  name:           James Pustejovsky
  site:           http://pusto.com
  avatar:         images/avatar.jpg
  bio:            "Computational Linguistics focuses on the study of language from a computational perspective. This dynamic field draws on artificial intelligence, computational and formal logic, linguistics, as well as philosophy, cognitive science, and psychology."
  email:          jamesp@brandeis.edu
  # Twitter nick for use in Twitter cards and follow button.
  twitter: # if no twitter in this config, the twitter follow button will be removed
  # GitHub nick for use in follow button in author block.
  github:

# Twitter account associated with the site if different from owner/author twitter account.
# Used in Twitter cards.
twitter:

# Social networking links used in author block underneath posts. Update and remove as you like.
social:
#  - title: "github"
#    url: "https://github.com/aron-bordin"
#  - title: "linkedin"
#    url: "https://br.linkedin.com/in/aronbordin"
#  - title: "youtube"
#    url: "https://www.youtube.com/channel/UCfnSek-9HPWOx5e2pH7VFgg"

# Background image to be tiled on all pages
background:

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/New_York
locale:      en_US
future:      true
highlighter: rouge
markdown:    kramdown
sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

# Amount of post to show on home page
paginate: 5
# paginated page
paginate_path: /updates/page:num/

# if true, shows the floatting share buttons
#float_share: true

# Octopress
# Default extensions
post_ext: md
page_ext: md
# Found in _templates/
post_layout: post
page_layout: page
# Format titles with titlecase?
titlecase: true

include: [".htaccess"]
exclude: ["demo/*", "lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
gems: [jekyll-paginate]
# theme: neo-hpstr-jekyll-theme
